### ISSUE TITLE
README directives

### ISSUE THREAD

**Issue by kamwoods** [timothyryanwalsh/brunnhilde#18]
As of BitCurator 1.7.106 (released 3/10/2016), the latest snapshot of HFSExplorer, along with the current (as of time of writing) releases of Siegfried and Brunnhilde are now installed by default. You may wish to test the release and (barring any issues) update the README directives here regarding running the tool in BitCurator.

**Comment by timothyryanwalsh** [comment]
Thanks, Kam! README is updated, and from a quick test everything seems to be working great.

In a future release, could we add either an icon for the CLI or the [Brunnhilde GUI](https://github.com/timothyryanwalsh/brunnhilde-gui) to the "Additional Tools" folder? (I'm planning to update the GUI for the latter soon, so it may make sense to wait on the latter)

**Comment by kamwoods** [comment]
Yes. I've added terminal launchers for both Siegfried and Brunnhilde in the "Forensics Tools" folder for now (upcoming release, 1.7.112), but a full reorg is coming soon since there are many other tools in there that aren't strictly forensics. Closing this issue for now. Will comment again as needed.
