### ISSUE TITLE
hfsexplorer files and mac SIP protection

### ISSUE THREAD

**Issue by bdietz** [timothyryanwalsh/brunnhilde#27]
Hey Tim,

Mac's SIP implementation means users cannot write to /usr/share, which is where hfsexplorer files are supposed to be. Users can continue to write to /usr/local. Is there a possible fix to this for brunnhilde?

https://support.apple.com/en-us/HT204899

Thanks!
Brian

**Comment by timothyryanwalsh** [comment]
Hi Brian, Sure thing! I'm working on a 1.6.0 release that will among other things bring some basic Windows support and an option not to generate hashes for files. I'll add this in to that release.

**Comment by timothyryanwalsh** [comment]
Fixed in https://github.com/timothyryanwalsh/brunnhilde/releases/tag/v1.6.0

**Comment by timothyryanwalsh** [comment]
Hi Brian - the expected location for the unhfs script in macOS is now /usr/local/share/hfsexplorer (it's still on the user to make sure that is properly installed). Should work better for you! I've tested it in macOS 10.12.6 and was able to install files into the correct directory without sudo rights.

**Comment by bdietz** [comment]
Thank you, Tim! I'll test this out today or early next week. As always, I
appreciate how open and responsive you are to these sorts of requests.
